@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

Container(frontend, "Веб-интерфейс")

Boundary(server, "Server") {
    Boundary(controlDevicesService, "Сервис для управления устройствами", "Java") {
        Component(controller, "Controller", "Spring Controller", "Kafka consumer. Подписывается на соответствующий Kafka топик и читает все команды (например: включить свет) и прокидывает команды дальше")
        Component(command, "Command component", "Spring Bean", "Обрабатывает все команды от контроллера, проверяет их валидность, если все ок забирает необходимые данные из Devices component и исполняет команду")
        Component(state, "Devices component", "Spring Bean", "Отвечает за конфигурацию всех текущих доступных устройств для управления (отопление, ворота, свет) и хранение их состояния")
    }

    Container(apiGateway, "Api-gateway", "Kong")
    ContainerDb(devicesDb, "Devices DB", "PostgreSQL")
}

Boundary(devices, "Devices") {
    System(device1, "Устройства отопления")
    System(device2, "Устройства освещения")
    System(device3, "Устройства управления воротами")
}

Rel(frontend, apiGateway, "Requests", "HTTPS")
Rel(apiGateway, controller, "Uses")
Rel(controller, command, "Uses")
Rel(command, state, "Uses")
Rel(command, device1, "Uses", "Telemetry")
Rel(command, device2, "Uses", "Telemetry")
Rel(command, device3, "Uses", "Telemetry")
Rel(command, devicesDb, "Read/write", "SQL")
Rel(state, devicesDb, "Read/write", "SQL")
@enduml